name: outputs

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  # Ziel von Outputs: Outputs von Job1 zu Job2 übergeben
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.schritt1.outputs.test }}
    steps:
      - id: schritt1
        run: echo "test=hallo" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: verwende output schritt1
        env:
          OUTPUT1: ${{ needs.job1.outputs.output1 }}
        run: echo "$OUTPUT1"
