name: outputs

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  # Ziel von Outputs: Outputs von Job1 zu Job2 übergeben
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.schritt1.outputs.test }}
      output2: ${{ steps.schritt2.outputs.test2 }}
    steps:
      - id: schritt1
        run: echo "test=hallo" >> "$GITHUB_OUTPUT"
      - id: schritt2
        run: echo "test2=Welt" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: verwende output schritt1
        env:
          OUTPUT1: ${{ needs.job1.outputs.output1 }}
        run: echo $OUTPUT1
      - name: verwende Output schritt2
        env:
          OUTPUT": ${{ needs.job1.outputs.output2 }}
        run: echo $OUTPUT2
